"""renamed Timestamps object to Timestamp

Revision ID: a271a8307bb2
Revises: c675ccd0f4e3
Create Date: 2019-08-14 14:18:03.617707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a271a8307bb2'
down_revision = 'c675ccd0f4e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timestamp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stamp_type', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timestamp_timestamp'), 'timestamp', ['timestamp'], unique=False)
    op.drop_index('ix_timestamps_timestamp', table_name='timestamps')
    op.drop_table('timestamps')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timestamps',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('stamp_type', sa.VARCHAR(length=140), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_timestamps_timestamp', 'timestamps', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_timestamp_timestamp'), table_name='timestamp')
    op.drop_table('timestamp')
    # ### end Alembic commands ###
